# Generated by Django 5.0.6 on 2024-07-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_role_name_remove_user_role_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('Booked', 'booked'), ('In Progress', 'in_progress'), ('Completed', 'completed'), ('Cancelled', 'cancelled')], max_length=30),
        ),
    ]
