# Generated by Django 4.2.13 on 2024-07-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_alter_ride_status_alter_role_name_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('en-route', 'En-route'), ('dropoff', 'Dropoff')], max_length=30),
        ),
    ]
