# Generated by Django 4.2.13 on 2024-07-31 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_alter_ride_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
